### ISSUE TITLE
Snekbox hangs while reading stdout from NsJail

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/snekbox#131]
## Description

Snekbox hangs while reading stdout from the NsJail processes. This is handled by `NsJail._consume_stdout()`. The specific line it hangs on is https://github.com/python-discord/snekbox/blob/94627e22c118060bdec1676f9dca16691617fa7d/snekbox/nsjail.py#L120

I believe this happens because the amount of bytes being read is larger than the amount that's in stdout. Hence, the `read()` call waits until enough bytes become available to satisfy the requested amount.

## Reproduction

Run the following commands

```sh
pipenv run devsh
python -m snekbox 'print("hello")' --time_limit 0
```

Wait and observe that Snekbox is not terminating. Press <kbd>ctrl</kbd> + <kbd>c</kbd> to see the following traceback appear

```py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mark/repos/python/snekbox/snekbox/__main__.py", line 35, in <module>
    main()
  File "/home/mark/repos/python/snekbox/snekbox/__main__.py", line 30, in main
    result = NsJail().python3(args.code, nsjail_args=args.nsjail_args, py_args=args.py_args)
  File "/home/mark/repos/python/snekbox/snekbox/nsjail.py", line 183, in python3
    output = self._consume_stdout(nsjail)
  File "/home/mark/repos/python/snekbox/snekbox/nsjail.py", line 120, in _consume_stdout
    chars = nsjail.stdout.read(READ_CHUNK_SIZE)
KeyboardInterrupt
```

**Comment by onerandomusername** [comment]
is the ``--time_limit 0`` key here?

**Comment by MarkKoz** [comment]
Not really. Without it, it was exiting with 137 cause it timed out. Although now that I'm trying again, I cannot reproduce this error at all...
