### ISSUE TITLE
Deployed pandas install is broken due to missing `six` dependency

### ISSUE THREAD

**Issue by bast0006** [python-discord/snekbox#89]
https://discord.com/channels/267624335836053506/635950537262759947/798160975810920458

running `!e import pandas` results in an error message:

```
Traceback (most recent call last):
  File "/snekbox/user_base/lib/python3.9/site-packages/pandas/__init__.py", line 29, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/snekbox/user_base/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/snekbox/user_base/lib/python3.9/site-packages/pandas/_libs/tslibs/__init__.py", line 30, in <module>
    from .conversion import OutOfBoundsTimedelta, localize_pydatetime
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/timezones.pyx", line 7, in init pandas._libs.tslibs.timezones
  File "/snekbox/user_base/lib/python3.9/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/snekbox/user_base/lib/python3.9/site-packages/dateutil/tz/tz.py", line 19, in <module>
    import six
ModuleNotFoundError: No module named 'six'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/snekbox/user_base/lib/python3.9/site-packages/pandas/__init__.py", line 33, in <module>
    raise ImportError(
ImportError: C extension: No module named 'six' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --force' to build the C extensions first.
```

**Comment by MarkKoz** [comment]
I'll leave this open since it needs a more proper fix. The current hotfix will always re-install existing dependencies, which makes all the volume stuff worthless.
